@startuml

skinparam backgroundcolor transparent
skinparam classFontSize 18
skinparam noteFontSize 18
skinparam arrowFontSize 18
skinparam classAttributeFontSize 18
skinparam packageFontSize 18

skinparam titleFontColor #5cb85c

'Title Module service_locator


namespace cu.datys.service_locator{


    class ServiceProviderLookup #FEFF99{
        + {static} <T> T lookup(Class<T> serviceProviderClass, ClassLoader classLoader)
        + {static} <T> List<T> lookupAll(Class<T> serviceProviderClass, ClassLoader classLoader)
    }

    ServiceProviderLookup -up-> java.util.ServiceLoader: use

    note right of ServiceProviderLookup
        List<T> list = lookupAll(
            serviceProviderClass, classLoader);
        if(list != null && !list.isEmpty())
            return list.get(0);
        return null;
    end note

    note bottom of ServiceProviderLookup
        List<T> list = new ArrayList<T>();
        ServiceLoader<T> loader = ServiceLoader.load(serviceProviderClass, classLoader);
        Iterator<T> iterator = loader.iterator();
        if(iterator.hasNext())
            iterator.forEachRemaining(list::add);
        return list;
    end note

}

namespace java.util{
    class ServiceLoader<S>{
        + {static} ServiceLoader load(Class service, ClassLoader loader)
    }
}


@enduml