@startuml

skinparam backgroundcolor transparent
skinparam classFontSize 18
skinparam noteFontSize 18
skinparam arrowFontSize 18
skinparam classAttributeFontSize 18
skinparam packageFontSize 18
skinparam classStereotypeFontSize 18

skinparam titleFontColor #5cb85c

'Title Module entity

interface IPerson extends cu.datys.null_object.spi.NullObject{
    + Integer getId()
    + void setId(Integer id)
    + String getName()
    + void setName(String name)
    + Integer getAge()
    + void setAge(Integer age)
}

class Person<<@Entity>> #FEFF99 implements IPerson, Serializable{
    - Integer id
    - String name
    - Integer age
}

namespace cu.datys.null_object.spi{
    interface NullObject{
        + default boolean isNull()
    }
}

@enduml